"""initial schema

Revision ID: f55a19fa38f4
Revises:
Create Date: 2026-07-29 18:45:24.881134
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f55a19fa38f4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("schema_version", sa.Integer(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("global_chronicle", sa.JSON(), nullable=False),
        sa.Column("world_state", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campaigns_is_active"), "campaigns", ["is_active"], unique=False)
    op.create_index(op.f("ix_campaigns_slug"), "campaigns", ["slug"], unique=True)
    op.create_table(
        "idempotency_records",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("scope", sa.String(length=160), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key", "scope"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("relative_path", sa.String(length=500), nullable=False),
        sa.Column("media_type", sa.String(length=120), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("license_name", sa.String(length=160), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("relative_path"),
    )
    op.create_index(op.f("ix_assets_campaign_id"), "assets", ["campaign_id"], unique=False)
    op.create_table(
        "background_jobs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=True),
        sa.Column("error_code", sa.String(length=120), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_background_jobs_campaign_id"), "background_jobs", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_background_jobs_kind"), "background_jobs", ["kind"], unique=False)
    op.create_index(op.f("ix_background_jobs_status"), "background_jobs", ["status"], unique=False)
    op.create_table(
        "characters",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("biography", sa.Text(), nullable=False),
        sa.Column("model_id", sa.String(length=160), nullable=True),
        sa.Column("sprite_asset_id", sa.String(length=36), nullable=True),
        sa.Column("voice_asset_id", sa.String(length=36), nullable=True),
        sa.Column("flip_x", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("hp_current", sa.Integer(), nullable=False),
        sa.Column("hp_max", sa.Integer(), nullable=False),
        sa.Column("mp_current", sa.Integer(), nullable=False),
        sa.Column("mp_max", sa.Integer(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("private_notes", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "slug", name="uq_character_campaign_slug"),
    )
    op.create_index(op.f("ix_characters_campaign_id"), "characters", ["campaign_id"], unique=False)
    op.create_index(op.f("ix_characters_is_active"), "characters", ["is_active"], unique=False)
    op.create_table(
        "game_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_game_events_campaign_id"), "game_events", ["campaign_id"], unique=False
    )
    op.create_index(op.f("ix_game_events_status"), "game_events", ["status"], unique=False)
    op.create_index(
        "uq_game_events_one_active_per_campaign",
        "game_events",
        ["campaign_id"],
        unique=True,
        sqlite_where=sa.text("status IN ('draft', 'active', 'finalizing')"),
        postgresql_where=sa.text("status IN ('draft', 'active', 'finalizing')"),
    )
    op.create_table(
        "realtime_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", "sequence", name="uq_realtime_campaign_sequence"),
    )
    op.create_index(
        "ix_realtime_campaign_sequence",
        "realtime_events",
        ["campaign_id", "sequence"],
        unique=False,
    )
    op.create_index(
        op.f("ix_realtime_events_campaign_id"), "realtime_events", ["campaign_id"], unique=False
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_items_character_id"), "inventory_items", ["character_id"], unique=False
    )
    op.create_table(
        "status_effects",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_status_effects_character_id"), "status_effects", ["character_id"], unique=False
    )
    op.create_table(
        "turns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("character_id", sa.String(length=36), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("actor_name", sa.String(length=160), nullable=False),
        sa.Column("actor_role", sa.String(length=64), nullable=False),
        sa.Column("thought", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("dice_roll", sa.Integer(), nullable=True),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["event_id"], ["game_events.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_id", "sequence", name="uq_turn_event_sequence"),
    )
    op.create_index(op.f("ix_turns_character_id"), "turns", ["character_id"], unique=False)
    op.create_index(op.f("ix_turns_event_id"), "turns", ["event_id"], unique=False)
    op.create_table(
        "observer_proposals",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campaign_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("turn_id", sa.String(length=36), nullable=False),
        sa.Column("gm_brief", sa.Text(), nullable=False),
        sa.Column("base_revision", sa.Integer(), nullable=False),
        sa.Column("operations", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["event_id"], ["game_events.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["turn_id"], ["turns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_observer_proposals_campaign_id"),
        "observer_proposals",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_observer_proposals_event_id"), "observer_proposals", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_observer_proposals_status"), "observer_proposals", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_observer_proposals_turn_id"), "observer_proposals", ["turn_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_observer_proposals_turn_id"), table_name="observer_proposals")
    op.drop_index(op.f("ix_observer_proposals_status"), table_name="observer_proposals")
    op.drop_index(op.f("ix_observer_proposals_event_id"), table_name="observer_proposals")
    op.drop_index(op.f("ix_observer_proposals_campaign_id"), table_name="observer_proposals")
    op.drop_table("observer_proposals")
    op.drop_index(op.f("ix_turns_event_id"), table_name="turns")
    op.drop_index(op.f("ix_turns_character_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index(op.f("ix_status_effects_character_id"), table_name="status_effects")
    op.drop_table("status_effects")
    op.drop_index(op.f("ix_inventory_items_character_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_realtime_events_campaign_id"), table_name="realtime_events")
    op.drop_index("ix_realtime_campaign_sequence", table_name="realtime_events")
    op.drop_table("realtime_events")
    op.drop_index(op.f("ix_game_events_status"), table_name="game_events")
    op.drop_index(op.f("ix_game_events_campaign_id"), table_name="game_events")
    op.drop_index("uq_game_events_one_active_per_campaign", table_name="game_events")
    op.drop_table("game_events")
    op.drop_index(op.f("ix_characters_is_active"), table_name="characters")
    op.drop_index(op.f("ix_characters_campaign_id"), table_name="characters")
    op.drop_table("characters")
    op.drop_index(op.f("ix_background_jobs_status"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_kind"), table_name="background_jobs")
    op.drop_index(op.f("ix_background_jobs_campaign_id"), table_name="background_jobs")
    op.drop_table("background_jobs")
    op.drop_index(op.f("ix_assets_campaign_id"), table_name="assets")
    op.drop_table("assets")
    op.drop_table("idempotency_records")
    op.drop_index(op.f("ix_campaigns_slug"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_is_active"), table_name="campaigns")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
